version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
    - postgres
    ports:
    - 5050:80
    ## you can change pgAdmin default username/password with below environment variables
    environment:
      PGADMIN_DEFAULT_EMAIL: donaldboulton@gmail.com
      PGADMIN_DEFAULT_PASSWORD: sysWB1h452891k
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.6
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: sysWB1h452891k
volumes:
  db_data: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIDATCCAemgAwIBAgIJehTS+srnY/Q0MA0GCSqGSIb3DQEBCwUAMB4xHDAaBgNV\nBAMTE21hbnNib29rcy5hdXRoMC5jb20wHhcNMTgwMjEyMTYyNTU4WhcNMzExMDIy\nMTYyNTU4WjAeMRwwGgYDVQQDExNtYW5zYm9va3MuYXV0aDAuY29tMIIBIjANBgkq\nhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlf1Adfc1pI12K15s28l5vq1hkTBbuNq9\nsDPH1W6VhAJiz9LgzUt60oJP07JTTwQGfczTH9f2N23u9l+d4RidiYYvyP3jDyZW\nedsp0/gOTqj2RdqAHy0wseo1IqrwzN6sZpSjF7KLTDkNySJWxYSXeciL+AeHbnX9\njhiAo/RptSBt3FDnLDBoHVwVnGhHWbftCW4ngbRrHrz7aWlStfd8rPHv8Mf5ylQc\nAJPkElM4DA+Ldj2XJP1XwnF6Vhrc6oitlgt0xEnSLrPPOSm2icKh8n2MrlJxr6am\nzQWzZWgiyJ9Xq3TztEQa9ckSa6u1NqwpL+UtZNl6EH6FQJWUxOH1tQIDAQABo0Iw\nQDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBT7yePZVwGAvDy7mnysNOJPMiUk\nTTAOBgNVHQ8BAf8EBAMCAoQwDQYJKoZIhvcNAQELBQADggEBAGA796qQ1BjPgphk\nWBQ7zLxepklNUJRvrZwdCG8hPemnncvPb4cU9PiEIn/D1hc1aXMN/0pxYyvn9MdH\nfq7mNH8DXt0OhoEOBXJjiDQ/xlUcDCbYipHvh8dzLe2o8PU8q5rHsl51jFJefKGR\n5wgLrz4ejiZ6bzy8JQaiF+hGMvy44XIQDk3GuE704UdzYv8bkycfEjqIO7Mta3WS\nXg3JseoQ+lDGtCx/9ivi9vDwQ0H5JJk2Gem41QJ+vD/d8wpv4+wBYlQeyiR2xlHC\naQFuE3DNUASMEsFLssJ+Xr8Q/EJ9FD9zgyj9rYwq9V1G44FoLfn6RIifRWw7Jlmx\nr9VO7JM=\n-----END CERTIFICATE-----\n"}'